---
name: TAP-Formatter-TeamCity
version: 0.01
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Emit test results as TeamCity service messages.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  TAP::Formatter::Base: 3.17
  TAP::Formatter::Session: 3.17
  TeamCity::BuildMessages: 0
build_requires:
  File::Spec: 0
  Test::More: 0
provides:
  TAP::Formatter::Session::TeamCity:
    file: lib/TAP/Formatter/Session/TeamCity.pm
    version: 0.01
  TAP::Formatter::TeamCity:
    file: lib/TAP/Formatter/TeamCity.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
